output_folder: Path to folder to save outputs
database_connection_parameters:
  database: Database name
  user: User account
  password: User password
  host: Host IP
  port: Host port
lsoa_shapefile:
  path: Path to LSOA shapefile
  id_column: Name of column containing LSOA IDs
year_filter: Optional year for filtering data
