# Configuration file specifying the segmentation and geographical level of the input data.
# All files here are assumed to be in a format ready for DVectors.
input_root_directory: I:\Data
output_directory: F:\Working\Land-Use\OUTPUTS_base_employment_hse
output_intermediate_outputs: False

base_data:
    lad_raw_4_digit_sic:
        file_path: HSL\2023\preprocessing\SIC4digit_byLA.hdf
        geographical_level: LAD2023+SCOTLANDLAD
        input_segments: [sic_4_digit]

    msoa_raw_2_digit_sic:
        file_path: HSL\2023\preprocessing\SICdiv_byMSOA.hdf
        geographical_level: MSOA2021+SCOTLAND-INT-ZONE
        input_segments: [sic_2_digit]

    lsoa_raw_1_digit_sic:
        file_path: HSL\2023\preprocessing\SICsec_byLSOA.hdf
        geographical_level: DZ2011+LSOA2021
        input_segments: [sic_1_digit]

    ons_sic_soc_jobs_lu:
        file_path: NorMITs Land Use\2023\import\ONS\industry_occupation\preprocessing\population_region_1sic_soc.hdf
        geographical_level: RGN2021+SCOTLANDRGN
        input_segments: [sic_1_digit, soc]

    wfj:
        file_path: NorMITs Land Use\2023\import\BRES2022\Employment\Employment Investigation\preprocessing\WFJ.hdf
        geographical_level: RGN2021+SCOTLANDRGN
        input_segments: [total]

    soc_4_factors:
        file_path: NorMITs Land Use\2023\import\SOC\preprocessing\Table 8 WFJ-adjusted Land Use SOC4.hdf
        geographical_level: RGN2021+SCOTLANDRGN
        input_segments: [total]

    employment_lsoa_distribution_factors:
        file_path: NorMITs Land Use\2023\import\Employment Attraction Distributions\sic mapped distributions\preprocessing\factors.hdf
        geographical_level: DZ2011+LSOA2021
        input_segments: [sic_1_digit]
