# Configuration file specifying the segmentation and geographical level of the input data.
# All files here are assumed to be in a format ready for DVectors.
# As the config is likely to be used for multiple files then the key will include the forecast year

input_root_directory: F:\Working\Land-Use\POPULATION_TARGETS\based_on_241220_Populationv2
output_directory: F:\Working\Land-Use\forecast_population_test_20250430
output_intermediate_outputs: False

base_year: 2023
forecast_years:
- 2033
- 2038
- 2043
- 2048
- 2053

run_for_regions:
- NW
- NE
- YH
- WM
- EM
- EoE
- Wales
- SW
- SE
- Lon
- Scotland

base_data:
    pop_output_directory:
        F:\Working\Land-Use\BASE_POPULATION_WITH_AGE_NTEM\based_on_241220_Populationv2
    household_output_directory:
        F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs
    base_pop_file_stem:
        Output P11
    base_households_file_stem:
        Output P13.3

forecast_data:
    population_targets:
        - file_path: pop_targets.hdf
          geographical_level: RGN2021
          input_segments: [age_ntem, g, soc]

        - file_path: soc_targets.hdf
          geographical_level: RGN2021
          input_segments: [g, soc]

        - file_path: pop_g_adults_targets.hdf
          geographical_level: LAD2021
          input_segments: [g, adults]

    household_targets:
        - file_path: household_children_targets.hdf
          geographical_level: RGN2021
          input_segments: [children]

        - file_path: household_single_adults_targets.hdf
          geographical_level: LAD2021
          input_segments: [adults]

        - file_path: household_totals_targets.hdf
          geographical_level: RGN2021
          input_segments: [total]

# testing
# add in order of priority (last being top priority)
population_segments_to_maintain:
# - accom_h
# - pop_emp
- ns_sec

household_segments_to_maintain:
# - ns_sec