# Configuration file specifying the segmentation and geographical level of the input data.
# All files here are assumed to be in a format ready for DVectors.
# As the config is likely to be used for multiple files then the key will include the forecast year

input_root_directory: I:\NorMITs Land Use\2023\import
output_directory: F:\Working\Land-Use\temp_forecast_population_testing_moving_to_config
output_intermediate_outputs: False
output_targets: True

base_year: 2023
forecast_years: 
- 2043
- 2053

run_for_regions:
- NW
- NE
- YH
- WM
- EM
- EoE
- Wales
- SW
- SE
- Lon
- Scotland

base_data:
    output_directory:
        F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs
    base_pop_file_stem:
        Output P11
    base_households_file_stem:
        Output P13.3

forecast_data:
    # growth factors from base in terms of muliplicative factors e.g., 1.2 means 20% increase
    pop_growth_factor:
        file_path: ONS\forecasting\pop_projs\preprocessing\pop_growth_factors_from_2023.hdf
        geographical_level: RGN2021
        input_segments: [age_ntem, g]

    # implied change in soc splits (soc 1-3) between bsae and forecast year
    # 0.05 would mean that combination increases by 5% (e.g., 30% to 35%) 
    soc_splits_change:
        file_path: Labour Market and Skills\LMS_SOC\preprocessing\soc_pp_change_from_2023.hdf
        geographical_level: RGN2021
        input_segments: [g, soc]
        # do we need to specify cut_read false here?

    pop_single_household_adult_growth_factor:
        file_path: ONS\forecasting\hh_projs\preprocessing\hh_1_adult_by_g_from_2023_factors.hdf
        geographical_level: LAD2019_EWS
        input_segments: [g, adults]
    
    pop_household_growth_factors:
        file_path: ONS\forecasting\hh_projs\preprocessing\hh_totals_from_2023_factors.hdf
        geographical_level: RGN2021
        input_segments: [total]   
    
    pop_household_children_growth_factors:
        file_path: ONS\forecasting\hh_projs\preprocessing\hh_children_from_2023_factors.hdf
        geographical_level: RGN2021
        input_segments: [children] 