# Config file for validation of NorCOM

# folder name of the actual NorCOM estimation outputs, and the reference that
# is in the name of the zonal data file
# (e.g. "I:\NorMITs NorCOM\Import\Zonal Data\zonal_logit_data_v36.csv")
estimation_version: v39

# master folder of all the different versions of the NorCOM estimation results
results_path: I:\NorMITs NorCOM\AECOM working

# path to the directory which contains all the version-specific zonal data outputs
zonal_lookups: I:\NorMITs NorCOM\Import\Zonal Data

# path to the P4.3 (2021) household dvectors that are an output of the
# base_population.py
input_dvectors: F:\Deliverables\Land-Use\241213_Population\01_Intermediate Files
file_reference: 4.3
year: 2021
#input_dvectors: F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs
#file_reference: 13.3
#year: 2023

# path to the dvector at LSOA level from the census website that reports
# total car ownership by 0, 1, 2+ cars from the census (this is ultimately
# what we want to match)
validation_dvector: I:\NorMITs Land Use\2023\import\ONS-validation\preprocessing\households_cars_lsoa_3.hdf

# path to store any validation outputs
output_path: I:\NorMITs NorCOM\Validation